- name: Test Docker
  hosts: all
  tasks:
     - name: Update et Upgrade
       shell: apt update; apt upgrade -y
     - name: Installation pré-requies
       apt: name={{ item }} update_cache=yes state=latest
       with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg2
        - software-properties-common

    
