- name: install Docker
  hosts: all
  tasks:
    - name: Ajout clef PGP
      shell: curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
    - name: Ajout repo Docker
      command: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian buster stable"
    - name: update
      shell: apt-get update
    - name: Install Docker
      apt: name={{ item }} update_cache=yes state=latest
      with_items:
       - docker-ce
       - docker-ce-cli
       - containerd.io

